✅Done: 3-module 2-task
js-tasks-ru/nodejs-20220421_alexey-jersey pull request #5
Opened 2022-05-12 20:35 UTC by AlexeyJersey

В связи с тем что неудачно сделал ребейз своей бранчи, решил откатиться на старый коммит что бы почистить историю, и случайно ресетнулся слишком далеко, поэтому пришлось закомитить еще и предыдущий таск который уже сдан. Сори.

2022-05-13 02:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-13 02:35 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-13 17:12 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-05-13 17:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-15 09:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-15 09:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-05-16 11:14 UTC, tadjik1 commented on 03-streams/04-file-server-post/server.js
> +        req.on('data', (chunk) => data = chunk);
получается каждый следующий чанк будет перезаписывать предыдущий? но тогда файл (состоящий из множества чанков) потеряет целостность

2022-05-16 11:15 UTC, tadjik1 requested changes
@AlexeyJersey отметил небольшой нюанс, который необходимо поправить, связанный с записью файла на диск

2022-05-16 17:42 UTC, AlexeyJersey commented on 03-streams/04-file-server-post/server.js
> +        req.on('data', (chunk) => data = chunk);
Ок, понял кажется

2022-05-16 17:42 UTC, AlexeyJersey commented
Обновил код, @tadjik1 посмотрите пожалуйста

2022-05-16 17:42 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-05-19 08:47 UTC, tadjik1 approved these changes
принимается :)

2022-05-19 08:48 UTC, merged